spring:
  jackson:
    deserialization:
      fail-on-unknown-properties=false:
dqualizer:
  rabbitmq:
    rqaDefinitionQueue: 'modeling'
    rqaExchange: 'modeler-translator'
    loadtestQueue: 'loadtest'
    loadtestExchange: 'translator-loadtest'

  mappingDirectory: 'mappings'

