server:
  port: 8080
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
dqualizer:
  messaging:
    queues:
      rqaConfigurationProducerQueue:
        name: 'rqaConfigurationProducer'
    exchanges:
      rqaConfigurationExchange:
        name: "rqaConfiguration"
  dqapi:
    host: 'localhost'
    port: '8099'

  mappingDirectory: 'mappings'

