dqualizer:
  messaging:
    queues: # Queues to connect to
      rqaDefinitionReceiverQueue:
        name: 'rqaDefinitionReceiver'
      rqaConfigurationProducerQueue:
        name: 'rqaConfiguration'

  mappingDirectory: 'mappings'

