server:
  port: 8080
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
dqualizer:
  messaging:
    queues:
      loadTestConfigurationQueue:
        name: 'loadTestConfigurationQueue'
      resilienceTestConfigurationQueue:
        name: 'resilienceTestConfigurationQueue'
    exchanges:
      rqaConfigurationExchange:
        name: "rqaConfiguration"
  dqapi:
    host: ${DQAPI_HOST:localhost}
    port: ${DQAPI_PORT:8099}

  mappingDirectory: 'mappings'

