server:
  port: 8080
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  rabbitmq:
    addresses: ${RABBITMQ_URI:-amqp://guest:guest@localhost:5432}

dqualizer:
  messaging:
    queues:
      rqaConfigurationProducerQueue:
        name: "rqaConfigurationProducer"
      k6:
        back-mapping: k6-back-mapping
    exchanges:
      rqaConfigurationExchange:
        name: "rqaConfiguration"

  dqapi:
    host: ${DQAPI_HOST:-localhost}
    port: ${DQAPI_PORT:-8099}

  mappingDirectory: "mappings"

influx:
  url: ${INFLUXDB_URL:-http://localhost:8086/}
  token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-my-token}
  org: ${DOCKER_INFLUXDB_INIT_ORG:-my-org}
  bucket: ${DOCKER_INFLUXDB_INIT_BUCKET:-my-bucket}

grafana:
  api:
    url: ${GRAFANA_URL:-http://localhost:3030/api}
    token: ${GRAFANA_TOKEN:-glsa_ME6K9ryRqs5C5J8MqfdhOO2j4u8xIjvo_44542600}

management:
  health:
    defaults:
      enabled: false
  metrics:
    export:
      influx:
        enabled: false
