server:
  port: 8080
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
dqualizer:
  messaging:
    queues: # Queues to connect to
      rqaDefinitionReceiverQueue:
        name: 'rqaDefinitionReceiver'
      rqaConfigurationProducerQueue:
        name: 'rqaConfiguration'
  dqapi:
    host: 'localhost'
    port: '8099'

  mappingDirectory: 'mappings'



repositories.mongohost...
