dqualizer:
  messaging:
    queues: # Queues to connect to
      rqaDefinitionReceiverQueue:
        name: "rqaDefinitionReceiver"
      rqaConfigurationProducerQueue:
        name: "rqaConfiguration"

  dqapi:
    host: "localhost"
    port: "8099"

  mappingDirectory: "mappings"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dqualizer