dqualizer:
  rabbitmq:
    rqaDefinitionQueue: 'modeling'
    rqaExchange: 'modeler-translator'
    loadtestQueue: 'loadtest'
    loadtestExchange: 'translator-loadtest'

  mappingDirectory: 'mapping'
