server:
  port: 8080
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
dqualizer:
  rabbitmq:
    rqaDefinitionQueue: 'modeling'
    rqaExchange: 'modeler-translator'
    loadtestQueue: 'loadtest'
    loadtestExchange: 'translator-loadtest'
  dqapi:
    host: 'localhost'
    port: '8099'

  mappingDirectory: 'mappings'

