name: CI/CD Pipeline of dqtranslator

on:
  push:

env:
  REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_test:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub Release Workflow"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew -PgprUsername=${{ github.repository_owner }} -PgprPassword=${{ secrets.GITHUB_TOKEN }} build

      - name: Prepare Release
        if : github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./gradlew -PgprUsername=${{ github.repository_owner }} -PgprPassword=${{ secrets.GITHUB_TOKEN }} -Prelease.useAutomaticVersion=true release

      - name: Distribute to GitHub Package Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./gradlew -PgprUsername=${{ github.repository_owner }} -PgprPassword=${{ secrets.GITHUB_TOKEN }} publish