name: CI/CD Pipeline of dqtranslator

on:
  push:

jobs:
  build_and_test:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub Release Workflow"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -PgprUsername=${{ github.repository_owner }}
            -PgprPassword=${{ secrets.GITHUB_TOKEN }}
            build

      - name: Prepare Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            release
            -PgprUsername=${{ github.repository_owner }}
            -PgprPassword=${{ secrets.GITHUB_TOKEN }}
            -Prelease.useAutomaticVersion=true

      - name: Distribute to GitHub Package Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publish
            -PgprUsername=${{ github.repository_owner }}
            -PgprPassword=${{ secrets.GITHUB_TOKEN }}
